const { test, expect } = require('@playwright/test')

const intersects = (a, b) => a.x < b.x + b.width && a.x + a.width > b.x && a.y < b.y + b.height && a.y + a.height > b.y

test('desktop flows, search, filter, validation and persistence', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Ваши проекты' })).toBeVisible()
  await expect(page.locator('.project-card')).toHaveCount(5)
  await page.getByRole('button', { name: 'Создать проект', exact: true }).click()
  await page.getByRole('button', { name: 'Создать проект', exact: true }).last().click()
  await expect(page.getByText('Введите название проекта')).toBeVisible()
  await expect(page.getByText('Добавьте короткое описание')).toBeVisible()
  await page.getByLabel('Название проекта *').fill('Тестовый проект')
  await page.getByLabel('Описание *').fill('Проверка сохранения данных в браузере')
  await page.getByRole('button', { name: 'Создать проект', exact: true }).last().click()
  await expect(page.getByText('Тестовый проект')).toBeVisible()
  await expect(page.locator('.project-card')).toHaveCount(6)
  await page.reload()
  await expect(page.getByText('Тестовый проект')).toBeVisible()
  await page.getByLabel('Поиск проектов').fill('магазин')
  await expect(page.getByText('Интернет-магазин одежды')).toBeVisible()
  await expect(page.getByText('Тестовый проект')).not.toBeVisible()
  await page.getByLabel('Очистить поиск').click()
  await page.getByLabel('Фильтр по статусу').selectOption({ label: 'Завершён' })
  await expect(page.locator('.project-card')).toHaveCount(1)
  await page.getByLabel('Поиск проектов').fill('не существует')
  await expect(page.getByText('Ничего не нашли')).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await expect(page.locator('.project-card')).toHaveCount(6)
})

test('toolbar is one row on desktop and does not overlap at 320px', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/')
  const search = page.locator('.search-box')
  const filter = page.getByLabel('Фильтр по статусу')
  const create = page.getByRole('button', { name: 'Создать проект', exact: true })
  const view = page.getByRole('button', { name: 'Сетка карточек' })
  const desktopBoxes = await Promise.all([search.boundingBox(), filter.boundingBox(), create.boundingBox(), view.boundingBox()])
  expect(desktopBoxes.every(Boolean)).toBeTruthy()
  const desktopY = desktopBoxes.map((box) => box.y)
  expect(Math.max(...desktopY) - Math.min(...desktopY)).toBeLessThan(4)

  await page.setViewportSize({ width: 320, height: 720 })
  await page.reload()
  const searchBox = await search.boundingBox()
  const createBox = await create.boundingBox()
  expect(searchBox).not.toBeNull()
  expect(createBox).not.toBeNull()
  expect(intersects(searchBox, createBox)).toBeFalsy()
  expect(createBox.y).toBeGreaterThan(searchBox.y + searchBox.height)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})
